### ISSUE TITLE
Python errors

### ISSUE THREAD

**Issue by gizamichal** [jonaslejon/malicious-pdf#3]
Hi, I get some error messages while using your program. I use Python3.

```
python3 malicious-pdf.py mydomain.com
  File "malicious-pdf.py", line 607
    except IndexError, e:
                     ^
SyntaxError: invalid syntax
```

'Fixed' by `except IndexError:` in line 607 but again:

```
python3 malicious-pdf.py mydomain.com
Creating PDF files..
Traceback (most recent call last):
  File "malicious-pdf.py", line 613, in <module>
    create_malpdf("test1.pdf", '\\\\' + '\\\\'  + host + '\\\\' )
  File "malicious-pdf.py", line 533, in create_malpdf
    file.write('''
TypeError: a bytes-like object is required, not 'str'
```

Can you explain what the cause of these problems is?

Regards

**Comment by BlueCanary-DM** [comment]
That's because it's written for Python 2.

**Comment by jonaslejon** [comment]
Thanks. This has been fixed
